# Generated by Django 4.2 on 2024-07-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0002_contactositio_formulariocontacto_inicio_nosotros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(default='Apellido', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombres',
            field=models.CharField(default='Apellido', max_length=200),
            preserve_default=False,
        ),
    ]
